### ISSUE TITLE
Search in Vietnamese returns wrong result

### ISSUE THREAD

**Issue by khuongdv** [bvaughn/react-select-fast-filter-options#15]
I tried to search some Vietnamese words, such as "Đà Nẵng" or "Việt Nam", the result seems not correct.

If I search some word using only Latin character, such as "company", search result is ok.

Please tell me how to get over this.

**Comment by bvaughn** [comment]
This library is [very tiny](https://github.com/bvaughn/react-select-fast-filter-options/blob/master/source/index.js) and just connects `react-select` to [`js-search`](https://github.com/bvaughn/js-search). This is mentioned [in the docs](https://github.com/bvaughn/react-select-fast-filter-options#configuration-options).

You could convert non-Latin characters to Latin characters by creating your own `indexStrategy if you want eg "ẵ" and "à" to fuzzy match "a". Or you could create your own `Tokenizer` if you want to fully support searching non-Latin characters. Check out issues bvaughn/js-search/issues/43 and bvaughn/js-search/issues/41 for good starting points if this is the route you want to go.

You may also want to scan through the [`js-search` documentation](https://github.com/bvaughn/js-search) too.

Good luck!
