### ISSUE TITLE
Multilingual support?

### ISSUE THREAD

**Issue by bratsos** [bvaughn/react-select-fast-filter-options#18]
Hello!

First of all, thanks for your great plugins!
I'm having some trouble while working with some non-latin words in labels, while using your fast filter plugin.

I've created a dumbed down version [here](https://codesandbox.io/s/wy92nvlrzk) with 4 languages, Greek, Russian, English and Chinese.

For Russian and English, search is working as expected, but for Greek and Chinese I'm not getting any results.

Is this a bug, or am I missing something?

Thanks in advance!

**Comment by bvaughn** [comment]
You are missing something, but you're in good company I guess. This question has come up often 😄  
* #4: encoding issue: korean is not working
* #15: Search in Vietnamese returns wrong result
* bvaughn/js-search/issues/53
* bvaughn/js-search/issues/43: UTF8 Support 
* bvaughn/js-search/issues/50: Searching for special characters
* bvaughn/js-search/issues/51: compatibility with Persian language
* bvaughn/js-search/issues/26: Punctuation and special characters seems to cause issues
* bvaughn/js-search/issues/11: Add multiple language support to SimpleTokenizer

At the bottom of the docs for `react-select-fast-filter-options`, there's a link to the underlying search implementation:
> For more information on available configuration options, see [`js-search` documentation](https://github.com/bvaughn/js-search).

That library exposes a simple [tokenizer](https://github.com/bvaughn/js-search#tokenization) that's capable of handling latin characters only. You can provide your own tokenizer if you want. A simple implementation you start with would be to split on spaces:

```js
searcher.tokenizer = {
  tokenize: (text) => text.split(/[\s]+/)
};
```

This would not work for Chinese, but I don't have the expertise or the time to create a Chinese-friendly tokenizer.

PRs to improve the documentation for this library (or `js-search`) are also welcome if you think you can make this clearer for others!

**Comment by aprilmintacpineda** [comment]
```js
haystack.tokenizer = {
  tokenize (text) {
    return Array.from(text);
  }
};
```

I find that the tokenizer above works for both Chinese and English. I'm not sure for the other languages.

You might need to polyfill `Array.from`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill

Why not use `Array.split('')`? --> https://stackoverflow.com/questions/4547609/how-do-you-get-a-string-to-a-character-array-in-javascript/34717402#34717402

**Comment by thoamsy** [comment]
For Chinese, people can use this regexp: 
```js
const regexpForChinese = /\p{sc=Han}|\p{Alpha}+/gu;
'This is my text. 这是我的测试'.match(regexpForChinese)
// ["This", "is", "my", "text", "这", "是", "我", "的", "测", "试"]
```
