### ISSUE TITLE
Add more indexes

### ISSUE THREAD

**Issue by freeranger** [bvaughn/react-select-fast-filter-options#2]
Hi,

My use case is  I  want a react-virtualized-select which who's options have a code, a description and an array of tags.
The selected value will be the code only.
The displayed text will be the code and the description with some formatting (may need to add a div or a span separating them).
The tags are not displayed.

When I type in the select box, I want it to match on code starts with the filter text OR description contains the filter text OR one of the tags exactly matches the filter text.
Ideally I would also like to be able to order them according to a custom ranking (e.g. exact match trumps contains, starts with trumps contains etc)

It seems I could achieve all this with js search but react-select-fast-filter-options doesn't expose enough of  it - either the ability to specify indexes explicitly (which is exposing implementation details, that you use js-search) or perhaps the ability to supply an array of 'label keys' representing the fields you want to be able to search on.

**Comment by bvaughn** [comment]
Check out [the docs](https://github.com/bvaughn/react-select-fast-filter-options#configuration-options). react-select-fast-filter-options exposes props for most of the underlying js-search configuration options.

> When I type in the select box, I want it to match on code starts with the filter text OR description contains the filter text OR one of the tags exactly matches the filter text.

The most straight-forward way of doing this would be to expose an `indexes` prop that allows you to specify custom search indexes (eg the equivalent of calling `jsSearch.addIndex('some-other-field')`). That seems like a reasonable addition for me to make.

> Ideally I would also like to be able to order them according to a custom ranking (e.g. exact match trumps contains, starts with trumps contains etc)

You can already do this by specifying your own [`ISearchIndex`](https://github.com/bvaughn/js-search/blob/master/source/search-index/search-index.ts) using the `searchIndex` property (eg js-search specifies [an index with TF-IDF ranking](https://github.com/bvaughn/js-search#tf-idf-ranking) for an example).

**Comment by bvaughn** [comment]
This change is available in 0.2.0. Check out [the new `indexes` prop](https://github.com/bvaughn/react-select-fast-filter-options#configuration-options)

**Comment by freeranger** [comment]
Great, thanks for the fast response Brian.
How would I achieve the goal of checking that some of the props contain the supplied value OR others equal the supplied value?  e.g. description _contains_ filter text, or one of the tags in the tag string array _exactly matches_ the filter text?

This is searching two different indexes with different matching criteria.

thanks

**Comment by bvaughn** [comment]
I don't really understand your question.

js-search will return any objects that match (partial or full match). You can specify your own index above, as I mentioned in my previous comments, if you want more fine-grained control over the results.

As for determining whether the text is an exact match for a tag or a partial match for a string... that's kind of out of scope of this component/lib.

**Comment by freeranger** [comment]
Hi

What what I am searching would be an array of objects that look like this:
```javascript
{
   code: '123',
   description: 'Foo bar with tag1 and other tags',
   tags: ['tag1','tag2', 'bar']
   ....other props
}
```
I want to search code, description, and tags fields, so I would add indexes for each of them
For the object above, searching for "2" would match the code field because it contains "2" but it would not have matched any of the tags because tag has to be an exact match.
Searching for "bar" would match this record on description (contains "bar") and tags (has a tag exactly equal to "bar")
Searching for "tag" would match on description (contains "tag") but not match any tags because again, it is not an exact match.
Searching for "tag1" would match both description (contains) and tags (exact match on tag1).

Does that explain better what I am trying to achieve?
Perhaps the question is more one for js-select per-se than for the fast filter component, but you are author of both and well, we're here now...
Is this something that js-select can do or is this too complex a requirement for js-select?
thanks.

**Comment by bvaughn** [comment]
Unfortunately the functionality you describe (fuzzy matching on some fields, exact matching on others) is not supported by js-search or react-select-fast-filter-options.

**Comment by bvaughn** [comment]
Actually you could accomplish this with js-search by creating 2 separate indexes: one with an exact match strategy (for tags) and one eye fuzzy match (the default) for the longer text field. Then you would need to run searches against both and take the union of their results.

This is too costumized for this component though. It's doable with js-search if you'd like to fork this lib and use the search directly though. :smile:
