### ISSUE TITLE
No Typings for typescript users

### ISSUE THREAD

**Issue by arijoon** [bvaughn/react-select-fast-filter-options#20]
Hi, can you please add typings for this library? 

currently I've used the following hack, but it would be very nice to have typings for it.

```ts
const createFilterOptions = (require('react-select-fast-filter-options') as any).default as (options: any) => any;
```

**Comment by bvaughn** [comment]
No, sorry. I don't use TypeScript.

You're welcome to create them yourself in the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped).
