### ISSUE TITLE
Consider removal of Array.prototype.includes use

### ISSUE THREAD

**Issue by jordonbiondo** [bvaughn/react-select-fast-filter-options#22]
Usage of `Array.prototype.includes` is the only thing standing in the way of this package being successfully used on IE11 without a polyfill or additional transformations.

A simple `for` loop with a `===` check would suffice. If you'd consider using an alternative I would be happy to provide a PR.

**Comment by bvaughn** [comment]
Put together a PR and I'll be happy to review it. 😄
