### ISSUE TITLE
encoding issue: korean is not working

### ISSUE THREAD

**Issue by landvibe** [bvaughn/react-select-fast-filter-options#4]
if the value of options is korean, the search is not working
for example...
const options = [
  {label: "한글1", value: "한글1"},
  {label: "한글2", value: "한글2"},
];
when i input '한', it does not show anything
I think it's an encoding issue.

**Comment by pmake** [comment]
I got the same issue with Chinese.

**Comment by bvaughn** [comment]
If either of you would like to look into this issue and submit a PR- probably against the underlying search lib, [bvaughn/js-search](https://github.com/bvaughn/js-search), I'd be happy to review it. Realistically I won't have time to look into it anytime soon.

**Comment by bvaughn** [comment]
Closing this issue since it is filed against the wrong project. Offer still stands to review a PR submitted to js-search though 😄
