### ISSUE TITLE
How to pass configuration params?

### ISSUE THREAD

**Issue by anshul2209** [bvaughn/react-select-fast-filter-options#6]
How do I pass 'searchIndex' / 'tokenizer' other than the defaults to rhe function ? The links are broken in the docs. @bvaughn

**Comment by bvaughn** [comment]
Just like the docs show, [here](https://github.com/bvaughn/react-select-fast-filter-options#advanced-configuration).

I've updated the deep links to work with js-search's latest folder structure.
