### ISSUE TITLE
Suggestion: Hide filterOptions implementation detail

### ISSUE THREAD

**Issue by Sharlaan** [bvaughn/react-select-fast-filter-options#7]
Just wondering if would be possible to :
a) make filterOptions directly coupled to this.props.options instead of exposing it as independant prop. This would make the component more user-friendly.
b) replace filterOptions with a new prop `customFilter`, defaulting to case insensitive search function (EDIT: or `js-search`). User can then inject a search function based on a different logic (ex: case sensistive).

**Comment by bvaughn** [comment]
> a) make filterOptions directly coupled to this.props.options instead of exposing it as independant prop. This would make the component more user-friendly.

I don't know what this means. `filterOptions` operates on `options`, so they are somewhat coupled (in that the filter function needs to be configured to at least know how to read the `options` data).

> b) replace `filterOptions` with a new prop `customFilter`, defaulting to case insensitive search function (EDIT: or js-search). User can then inject a search function based on a different logic (ex: case sensistive).

What would this mean? There would be 2 props that both do the same thing, with conflicting defaults?

js-search is already used under the hood and you can configure it further as shown [in the docs](https://github.com/bvaughn/react-select-fast-filter-options#configuration-options). If you want case-sensitive search then you can pass in an instance of [`CaseSensitiveSanitizer`](https://github.com/bvaughn/js-search/blob/master/source/Sanitizer/CaseSensitiveSanitizer.js) as the `sanitizer` prop.

**Comment by Sharlaan** [comment]
a) I simply meant how about exposing only the public props.options, then do your thing with filterOptions(props.options) internally, it seems to be implementation details or i missed something ?

b) again this were a simplification suggestion against 2-3 props into one single ?

**Comment by bvaughn** [comment]
`filterOptions` can't always be automatic. The [docs](https://github.com/bvaughn/react-select-fast-filter-options#configuration-options) show the ways you can configure it. For example, what if the label or values fields are different for someone's options?

**Comment by Sharlaan** [comment]
options passed to props.options and passed to filterOptions MUST be the same ?
By default, i guess js-search filters based on option.label while selection is based on option.value, both prop being required right ?
If i'm correct, then it should be factorisable ?

**Comment by bvaughn** [comment]
I don't see the problem with the current API to be honest. It's pretty simple.

If you have concrete ideas to improve it, I would be happy to review a PR. Otherwise I think it's okay as-is. 😄

**Comment by Sharlaan** [comment]
ok i apologize :
after rereading multiple times, i realized this isnot a component but a simple reusable filtering function you are exposing in this repo.
I realized especially after noticing the examples were using different select components.

My bad you can close.

**Comment by bvaughn** [comment]
No problem. Sorry for the confusion!

This library just connects js-search and react-select for people who don't want to wire them up manually. 😄
