### ISSUE TITLE
Suggestion: another way to provide options

### ISSUE THREAD

**Issue by Sharlaan** [bvaughn/react-select-fast-filter-options#8]
Would it be possible to propose user with injecting his options as {children}, where children is an array of customised nodes exposing the required value and text props ?

**Comment by bvaughn** [comment]
I don't think this is something I want to support. This lib exists to help speed up filtering _a lot_ of data. I don't think it's wise to pass _a lot_ of data through React's pipeline, where it has to be inspected/diffed for changes, particularly when we know it's not all going to be rendered. I think passing it as a prop is better for performance and is fairly syntactically straight forward.
