### ISSUE TITLE
Filtering more than one Lakh records | Unresponsive

### ISSUE THREAD

**Issue by Ajaybhardwaj7** [bvaughn/react-select-fast-filter-options#9]
I have a use case in which I push around 1 lakh records in select box using Virtualized select. It behaves very fast while scrolling and selection. But I also need a filter, for which I am using react-select-fast-filter-options ,
when I pass filterOptions as createFilterOptions(records), the select hangs for more than 10 seconds and behaves quite unresponsive during selection as well.
Is there a way to resolve this. records are simply {label:"XYZ",value:"XYZ"}

"react-select": "^1.0.0-rc.3",
 "react-select-fast-filter-options": "^0.2.1",
"react-virtualized-select": "^3.0.1",

**Comment by bvaughn** [comment]
Should be fast. [Demo](https://bvaughn.github.io/react-select-fast-filter-options/) shows 10,000 objects being indexed without any lag. I suspect something else is going on in your project but it's hard to know without seeing source.

Please point me at a Plnkr or something where I can see the code, and see the bug happening, and I'll be happy to take a look. 😄 Closing for now though as this isn't really an actionable issue.

> when I pass filterOptions as createFilterOptions(records), the select hangs for more than 10 seconds 

PS just in case you're _literally_ calling `createFilterOptions(records)` - you should be calling `createFilterOptions({ options: records })`

**Comment by Ajaybhardwaj7** [comment]
I have uploaded the sample on plunkr at http://plnkr.co/edit/iY19tMj2psdz5J7w3Ydv?p=preview 
I have two issues.
1. CreateFilterOptions do take around 6 seconds to create filter index of 1 lakh records and blocks the UI thread post that filtering is absolutely fine.
2. Post selection of record, takes again 6 seconds to render. The reason being indexing happening second time as record is being re rendered.
In my case the indexing of 1,17,000 records blocks the UI thread for 10 seconds which is affecting user exp.

**Comment by bvaughn** [comment]
Ah. I am not familiar with the unit lakh. I think it's 100,000? Anyway, yes, indexing 117,000 records could cause some lag as the underlying search library (js-search) runs on the UI thread. (It's heavily optimized but still...)

One thing I want to point out though is that you definitely shouldn't be creating the filtered options set in the render method. This causes the index to be recreated on each render which is not good for performance. So for example:
http://plnkr.co/edit/uYEJXD?p=preview

As for the several seconds of hanging, you may have better luck using another library of mine, [js-worker-search](https://github.com/bvaughn/js-worker-search/). It's a bit less configurable but it runs in a web-worker so it would perform better.
